// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlojmuzydjsojfctljwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsb2ptdXp5ZGpzb2pmY3RsandrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTA0ODgsImV4cCI6MjA2OTM4NjQ4OH0.CVv58XuPNZIpif24cQWqoUP1LbAppBcjbYdJQV2HJf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});